FROM balenalib/%%RESIN_MACHINE_NAME%%-alpine:latest

WORKDIR /usr/src/app

RUN apk update && apk add bash python3 lockfile-progs --no-cache && \
    python3 -m venv venv && \
    source venv/bin/activate && \
    pip install --upgrade pip && \
    pip install flask

COPY . ./

CMD ["bash", "start.sh"]
