FROM balenalib/%%RESIN_MACHINE_NAME%%-alpine:latest

RUN apk update && apk add bash py-pip lockfile-progs --no-cache && \
    pip install --upgrade pip && \
    pip install flask

WORKDIR /usr/src/app

COPY . ./

CMD ["bash", "start.sh"]
